name: Resistance-API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build & Test
      run: mvn -B package --file pom.xml

    - name: Provide application actual version
      id: vars
      run: echo ::set-output name=api_version::$(cat pom.xml | grep "<version>.*</version>" | head -2 |awk -F'[><]' '{print $3}' | sed -n '2p')

    - name: Build docker image & Publish in docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/resistance-api
        tags: latest, ${{ steps.vars.outputs.api_version }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
